AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spring Boot Lambda Function

Parameters:
  CognitoUserPoolId:
    Type: String
    Description: "The ID of the Cognito User Pool."
  CognitoAppClientId:
    Type: String
    Description: "The ID of the Cognito User Pool App Client."

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.java.com.example.LambdaHandler::handleRequest
      Runtime: java21
      CodeUri: ./build/libs/backend-0.0.1-SNAPSHOT.jar
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /hello
            Method: GET
            Auth:
              Authorizer: !Ref ApiGatewayCognitoAuthorizer
              AuthorizationScopes:
                - "email"
                - "openid"
                - "profile"

  ApiGatewayCognitoAuthorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      Name: CognitoAuthorizer
      ApiId: !Ref HttpApi
      AuthorizerType: JWT
      IdentitySource:
        - "$request.header.Authorization"
      JwtConfiguration:
        Audience:
          - !Ref CognitoAppClientId
        Issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPoolId}"

Outputs:
  ApiURL:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"